sudo: required

services:
  - dockerfile

before_install:
  - docker build -t imarichev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true imarichev/react-test npm test


after_success:
  - docker build -t imarichev/multi-client ./client
  - docker build -t imarichev/multi-nginx ./nginx
  - docker build -t imarichev/multi-server ./server
  - docker build -t imarichev/multi-worker ./worker 
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push imarichev/multi-client
  - docker push imarichev/multi-nginx
  - docker push imarichev/multi-server
  - docker push imarichev/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-038934243435'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY