sudo: required
services:
  - dockerfile

before_install:
  - docker build -t imarichev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true imarichev/react-test npm test


after_success:
  - docker build -t imarichev/multi-client ./client
  - docker build -t imarichev/multi-nginx ./nginx
  - docker build -t imarichev/multi-server ./server
  - docker build -t imarichev/multi-worker ./worker 
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push imarichev/multi-client
  - docker push imarichev/multi-nginx
  - docker push imarichev/multi-server
  - docker push imarichev/multi-worker